apiVersion: v1
kind: ConfigMap
metadata:
  name: mcp-server-config
  namespace: mcp-server
data:
  application-prod.properties: |
    server.port=8080
    server.servlet.context-path=/mcp
    spring.profiles.active=prod
    spring.ai.mcp.server.name=HelloMCPServer-K8s
    spring.ai.mcp.server.description=Kubernetes deployed MCP server
    spring.ai.mcp.server.version=1.0.0
    logging.level.com.shan.hello_mcp=INFO
    management.endpoints.web.exposure.include=health,info,metrics,prometheus
    management.endpoint.health.probes.enabled=true
    management.server.port=9090

